name: Deploy master to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.G_USER_NAME }}
      PASSWORD: ${{ secrets.G_TOKEN }}
      REPO_URL: https://${USERNAME}:${PASSWORD}@github.com/lwinmoehein/X-Money-Tracker-Backend


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
            git config --global user.email ${{ secrets.G_EMAIL }}
            git config --global user.name ${{ secrets.G_USER_NAME}}
            git config --global credential.helper '!f() { sleep 1; echo "password=$G_TOKEN"; }; f'

      - name: Deploy master branch to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/X-Money-Tracker-Backend &&
            git checkout master &&
            git pull ${REPO_URL} master &&
            composer install &&
            yes | php artisan migrate &&
            php artisan optimize
          known_hosts: ${{ secrets.SERVER_HOST }}
